### PR TITLE
Pin task

### PR DESCRIPTION
**Pull request by MonCaptain**
added pin icon for each task and some css.

### CODE REVIEW

**Review by Rebecca-CYLi — CHANGES_REQUESTED** [review]
missing info in right side panel, please fill it out

**Comment by MonCaptain** [comment]
> missing info in right side panel, please fill it out

I've done so a few minutes already, can you try refreshing?

**Review by Rebecca-CYLi — APPROVED** [review]
cool, G2G

**Review by MonCaptain — COMMENTED** [review]
re-examined changes made

**Comment by MonCaptain** [comment]
> 

Thank you kindly

**Pull request merged**
