### PR TITLE
User authentication

### PR DESCRIPTION
**Pull request by MonCaptain**
This branch contains db tables, user authentication model and endpoints. It also contains set up for other routes and models related to tasks and sessions.

### CODE REVIEW

**Review by Rebecca-CYLi — CHANGES_REQUESTED** [review]
did y'all forget to put the node_modules into the .gitignore? pls check for both backend and frontend dir

**Comment by ShehabMohsen** [comment]
>

**Comment by MonCaptain** [comment]
We included node_modules in our .gitignore file but for some reason they still keep getting pushed.

**Review by Rebecca-CYLi — APPROVED** [review]
cool, new files + rm'ed node_modules. lgtm

**Pull request merged**
