### PR TITLE
Adding Tasks on Sidebar

### PR DESCRIPTION
**Pull request by MonCaptain**
Can now create/delete tasks on the front end. Can also mark them as complete. Additionally, utilized local storage to allow task list to remain unchanged upon refreshing the page.

### CODE REVIEW

**Review by LifeBringer — CHANGES_REQUESTED** [review]
Remove commented out code.

**Comment by MonCaptain** [comment]
> Remove commented out code.

Can you tell me where's the commented out code? The comments I made within the TodoTab directory are not code, but my own documentation for functions/variables/etc.

**Comment by LifeBringer** [comment]
Could you resolve the merge conflicts?

**Review by MonCaptain — COMMENTED** [review]
I have reviewed the changes and made sure that nothing suspicious is going on.

**Review by Rebecca-CYLi — APPROVED** [review]
Try to keep it simple to one or two components, also add the package-lock.json to gitignore next time.

LGTM

**Review by MonCaptain — COMMENTED** [review]
Review Done

**Pull request merged**
